version: "3"
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: bundle exec jekyll serve --config _config.yml,_config.docker.yml
    image: beautiful-jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"